### ISSUE TITLE
Game crashes, usually shortly after 1 in game cycle

### ISSUE THREAD

**Issue by Anonymous-Floof** [SnackJunkie/ONI-Mods#3]
[Player-prev.log](https://github.com/SnackJunkie/ONI-Mods/files/12228614/Player-prev.log)
I believe it's a conflict of some sort with the mod "Diseases Restored". 
If it's nothing you can fix (and my conflict assumption is correct), I'll bring this issue up with the maker of that mod as well

EDIT: never mind, it's that mod causing issues

**Comment by SnackJunkie** [comment]
I see you closed this but thought you might like to know the cause and fix. Diseases Restored crashes the game whenever a dupe gets hypothermia. There is a Diseases Restored - Fixed on the workshop that resolves this issue.
