### ISSUE TITLE
Request: Modification of Supply Errands for Reworked Incubator

### ISSUE THREAD

**Issue by TroublesomeCorvid** [SnackJunkie/ONI-Mods#5]
One of the more annoying things in the game is that Dupes will supply eggs to Incubators that are disabled by automation.  Is there any way to add in a feature for your mod that will stop this errand from being generated when the incubator is disabled?

**Comment by SnackJunkie** [comment]
That's a good point, I'll look into it when I have the time

**Comment by SnackJunkie** [comment]
Looks doable, but I don't think I can differentiate between disabled by automation and unpowered. So it would only generate the supply errand if it's powered.

**Comment by TroublesomeCorvid** [comment]
Well, if nothing else, that gives me the idea of simply running automation from a critter sensor in the ranch to a power shut-off or transformer supplying the incubators.  So if it does prove undoable with the code as it is now, then there is at least that.

**Comment by SnackJunkie** [comment]
It actually occurs to me that there are times you might want to use an unpowered incubator to hold an egg, and that wouldn't work if I make that change. I'll have to see if I *can* distinguish between unpowered and disabled by automation.

**Comment by TroublesomeCorvid** [comment]
Well, I just discovered that dupes will deliver eggs to incubators regardless of whether they're powered or not.  So whatever you tweak in the code to alter the assignment of tasks, it will probably work either way.
