### ISSUE TITLE
Game crash when modifying a rocket

### ISSUE THREAD

**Issue by jenden0** [SnackJunkie/ONI-Mods#6]
**Mod**
Pipe Flow Overlay

**Describe the bug**
I was working on a rocket, specifically adding a cargo module above my command module. The game then suddenly crashed with a stack trace from Pipe Flow Overlay. I was not in the plumbing overlay view at the time.
Stack Trace:
```
NullReferenceException

Pipe_Flow_Overlay.PipeFlowOverlayMod.AddFlowDirection[T] (UnityEngine.GameObject conduitGO, T flow, System.Boolean active) (at <53915c9c226340b9a6c1b55be7803258>:0)
Pipe_Flow_Overlay.PipeFlowOverlayMod+<>c__DisplayClass40_1.<AddOrUpdateGasConduitFlowDirection>b__1 (UnityEngine.GameObject _) (at <53915c9c226340b9a6c1b55be7803258>:0)
System.Collections.Concurrent.ConcurrentDictionary`2[TKey,TValue].AddOrUpdate (TKey key, System.Func`2[T,TResult] addValueFactory, System.Func`3[T1,T2,TResult] updateValueFactory) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Pipe_Flow_Overlay.PipeFlowOverlayMod+<>c__DisplayClass40_0.<AddOrUpdateGasConduitFlowDirection>b__0 () (at <53915c9c226340b9a6c1b55be7803258>:0)
Pipe_Flow_Overlay.PipeFlowOverlayMod.Update () (at <53915c9c226340b9a6c1b55be7803258>:0)
Pipe_Flow_Overlay.Patches+Game_Update_Patch.Postfix () (at <53915c9c226340b9a6c1b55be7803258>:0)
(wrapper dynamic-method) Game.Game.Update_Patch1(Game)

Build: U48-568201-S
```

**To Reproduce**
N/A: I tried reproducing it but could not.

**Expected behavior**
Game should not crash.

**Player.log**
[Player.log](https://github.com/SnackJunkie/ONI-Mods/files/12389409/Player.log)

Add your player.log file here

**Screenshots**
This is the particular rocket I was modifying (leftmost one). This is from the previous autosave, which is shortly before the crash.
![ONI_broken_pipe](https://github.com/SnackJunkie/ONI-Mods/assets/11865198/3b9999fa-401f-4168-b4b6-be0ad88de53a)

**Comment by demosdemon** [comment]
I'm able to repro this by simply deconstructing a command module with piping. E.g., when I deconstruct a solo spacefarer with a simple ventilation loop from the input node to a gas vent on the floor (co2 deleter).
