### ISSUE TITLE
Potential crash in PipeFlowOverlay

### ISSUE THREAD

**Issue by jenden0** [SnackJunkie/ONI-Mods#8]
**Mod**
PipeFlowOverlay

**Describe the bug**
While changing the piping of my nuclear reactor (including constructing/deconstructing multiple pipes and conduction panels) the game suddenly crashed. The crash report implicated PipeFlowOverlay and FastTrack, and I'm not sure which is the real culprit so I'm filing bugs with both.

**To Reproduce**
Unknown

**Expected behavior**
Game should not crash

**Player.log**
[Player.log](https://github.com/SnackJunkie/ONI-Mods/files/12568114/Player.log)

**Screenshots**

**Comment by SnackJunkie** [comment]
Doesn't look related to PipeFlowOverlay, and it appears you're somehow using an outdated version of the mod. The error is coming from a common method my mod is no longer hooking into. It's simply flagged because it had a patch on the method that failed.
